name: Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install robotframework
        pip install robotframework-seleniumlibrary
        pip install allure-robotframework
        sudo apt-get install -y default-jre  # for Allure CLI
        curl -o allure-2.27.0.tgz -L https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
        tar -xvzf allure-2.27.0.tgz
        sudo mv allure-2.27.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure

    - name: Run Robot tests with Allure
      run: |
        robot --listener "allure_robotframework;output_dir=allure-results" test/

    - name: Generate Allure Report (HTML)
      run: |
        allure generate allure-results --clean -o allure-report

    - name: Upload Allure report artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report
